### ISSUE TITLE
请问如何自定义下载文件夹名字

### ISSUE THREAD

**Issue by rm5ca** [hect0x7/JMComic-Crawler-Python#114]
我正在使用一个名为 jmcomic 的模块（或库）。该模块中有一个函数 download_album，我知道有JmOption，但我不知道参数

现有数据结构：

albumID: 代表相册的唯一标识。
photoID: 代表相册内照片的唯一标识。

如果 146417 书本内有 390572 和 390573 
 
当我调用 jmcomic.download_album('146417') 时，要如何自定义下载文件夹名字

146417 (这是相册ID)
│
├── 390572 (这是相册内的一个照片ID)
│
└── 390573 (这是相册内的另一个照片ID)

当前直接下载会出现这样 

书本名字 (这是相册ID)
│
├── 第一话 我是大姐 (这是相册内的一个照片ID)
│
└── 第二话 我是大哥(这是相册内的另一个照片ID)

谢谢

**Comment by hect0x7** [comment]
1. 创建一个option的配置文件，名为 `myoption.yml`，放在python脚本目录下，文件内容如下
```yml
dir_rule:
  base_dir: ${workspace}
  rule: Bd_Aid_Pid
```

2. 使用如下python代码
```python
import jmcomic

option = jmcomic.create_option('./myoption.yml')

jmcomic.download_album('146417', option)

```

- 最终效果如下：
```

146417 (albumID)
│
├── 390572 (photoID)
    ├── 00001.webp （该章节的图片）
│
└── 390573 (photoID)
    ├── 00001.webp （该章节的图片）
```

如此配置的原因和其他用法，你可以参考: https://github.com/hect0x7/JMComic-Crawler-Python/blob/master/assets/config/%E5%B8%B8%E7%94%A8%E9%85%8D%E7%BD%AE%E4%BB%8B%E7%BB%8D.yml

**Comment by rm5ca** [comment]
感谢您的回复，请问我可以小小赞助项目吗？请你提供email 给我，或者请你email 我 james.8881a@gmail.com

**Comment by hect0x7** [comment]
> 感谢您的回复，请问我可以小小赞助项目吗？请你提供email 给我，或者请你email 我 [james.8881a@gmail.com](mailto:james.8881a@gmail.com)

感谢你的心意，也请给我一点时间让我考虑一下赞助的事情，如果我也有意愿我会email你的，蟹蟹~

**Comment by rm5ca** [comment]
> > 感谢您的回复，请问我可以小小赞助项目吗？请你提供email 给我，或者请你email 我 [james.8881a@gmail.com](mailto:james.8881a@gmail.com)
> 
> 感谢你的心意，也请给我一点时间让我考虑一下赞助的事情，如果我也有意愿我会email你的，蟹蟹~

请你记录我的email 后告诉我，我怕等下太多广告和骗子，谢谢你

**Comment by hect0x7** [comment]
我的email: myzzkkzz155@gmail.com，如果你收到了也回复我下，我会立刻把这个issue删除，上面的代码如果有需要我会再贴一次到你的issue
