### ISSUE TITLE
增加搜索本子时可以选择排序规则

### ISSUE THREAD

**Issue by bjssliu** [hect0x7/JMComic-Crawler-Python#124]
能否在搜索本子的时候可以选择按照时间、观看次数、点击喜欢、总页数等进行排序呢。

**Comment by hect0x7** [comment]
可以是可以，感觉不怎么用得到，还没做。你有兴趣实现一下吗？可以提PR

**Comment by hect0x7** [comment]
v2.2.5 已实现JM搜索的全部功能，包括排序和时间区间
