### ISSUE TITLE
ip地区禁止访问/爬虫被识别

### ISSUE THREAD

**Issue by pannifeng** [hect0x7/JMComic-Crawler-Python#142]
![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/60848029/28f33c0c-f0f9-422b-a86e-e2081e940b6d)

**Comment by hect0x7** [comment]
你的ip地区？

**Comment by pannifeng** [comment]
> 你的ip地区？

试了美国、日本、香港的代理都这样，手动访问会跳cf的盾
![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/60848029/6007225a-53f0-47ef-a2e4-9b7ed5f82c7b)

**Comment by hect0x7** [comment]
美日的ip这个域名会被ban，香港的应该不会，你确定配了代理配置？

**Comment by pannifeng** [comment]
> 你的ip地区？
不咋会用python，贴一下配置看看是不是哪没配好
![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/60848029/6f1f7efc-d604-4ce8-b3f1-d8d0f3530a2d)
![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/60848029/1e3c61eb-9379-4c0b-8944-78dfaaa9b508)

**Comment by pannifeng** [comment]
> 美日的ip这个域名会被ban，香港的应该不会配置，你确定配了代理吗？

确定，因为刚开始没配置代理直接就是连不上
![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/60848029/baaea444-18ca-4ff1-8ad2-11d7c7ca208b)

**Comment by hect0x7** [comment]
代理配的是对的，那就比较奇怪了，应该还是你ip的问题。
访问这个网站看看你香港的ip是不是真的在香港 https://ipinfo.io/，如果真的是香港，那就可能是ip被ban了吧，换其他的ip

**Comment by pannifeng** [comment]
> 代理配的是对的，那就比较奇怪了，应该还是你ip的问题。 访问这个网站看看你香港的ip是不是真的在香港 https://ipinfo.io/，如果真的是香港，那就可能是ip被ban了吧，换其他的ip

刚看了下，香港的代理过期了，有那个域名能用美国ip访问吗

**Comment by hect0x7** [comment]
> > 代理配的是对的，那就比较奇怪了，应该还是你ip的问题。 访问这个网站看看你香港的ip是不是真的在香港 [https://ipinfo.io/，如果真的是香港，那就可能是ip被ban了吧，换其他的ip](https://ipinfo.io/%EF%BC%8C%E5%A6%82%E6%9E%9C%E7%9C%9F%E7%9A%84%E6%98%AF%E9%A6%99%E6%B8%AF%EF%BC%8C%E9%82%A3%E5%B0%B1%E5%8F%AF%E8%83%BD%E6%98%AFip%E8%A2%ABban%E4%BA%86%E5%90%A7%EF%BC%8C%E6%8D%A2%E5%85%B6%E4%BB%96%E7%9A%84ip)
> 
> 刚看了下，香港的代理过期了，有那个域名能用美国ip访问吗

参考GitHub Actions的配置 [https://github.com/hect0x7/JMComic-Crawler-Python/blob/master/assets/config/option_workflow_download.yml]()

**Comment by pannifeng** [comment]
> > > 代理配的是对的，那就比较奇怪了，应该还是你ip的问题。 访问这个网站看看你香港的ip是不是真的在香港 [https://ipinfo.io/，如果真的是香港，那就可能是ip被ban了吧，换其他的ip](https://ipinfo.io/%EF%BC%8C%E5%A6%82%E6%9E%9C%E7%9C%9F%E7%9A%84%E6%98%AF%E9%A6%99%E6%B8%AF%EF%BC%8C%E9%82%A3%E5%B0%B1%E5%8F%AF%E8%83%BD%E6%98%AFip%E8%A2%ABban%E4%BA%86%E5%90%A7%EF%BC%8C%E6%8D%A2%E5%85%B6%E4%BB%96%E7%9A%84ip)
> > 
> > 
> > 刚看了下，香港的代理过期了，有那个域名能用美国ip访问吗
> 
> 参考GitHub Actions的配置 [option_workflow_download.yml](https://github.com/hect0x7/JMComic-Crawler-Python/blob/master/assets/config/option_workflow_download.yml)

意思是用action在线下载吗？刚试了下下载的图片默认是webp的，在哪个地方设置action
的下载格式呢

**Comment by hect0x7** [comment]
> > > > 代理配的是对的，那就比较奇怪了，应该还是你ip的问题。 访问这个网站看看你香港的ip是不是真的在香港 [https://ipinfo.io/，如果真的是香港，那就可能是ip被ban了吧，换其他的ip](https://ipinfo.io/%EF%BC%8C%E5%A6%82%E6%9E%9C%E7%9C%9F%E7%9A%84%E6%98%AF%E9%A6%99%E6%B8%AF%EF%BC%8C%E9%82%A3%E5%B0%B1%E5%8F%AF%E8%83%BD%E6%98%AFip%E8%A2%ABban%E4%BA%86%E5%90%A7%EF%BC%8C%E6%8D%A2%E5%85%B6%E4%BB%96%E7%9A%84ip)
> > > 
> > > 
> > > 刚看了下，香港的代理过期了，有那个域名能用美国ip访问吗
> > 
> > 
> > 参考GitHub Actions的配置 [option_workflow_download.yml](https://github.com/hect0x7/JMComic-Crawler-Python/blob/master/assets/config/option_workflow_download.yml)
> 
> 意思是用action在线下载吗？刚试了下下载的图片默认是webp的，在哪个地方设置action 的下载格式呢

不是，是参考actions的配置文件🤣 option_workflow_download.yml
在哪个地方设置action 的下载格式 -> 也是改actions的配置文件

**Comment by pannifeng** [comment]
> > > > > 代理配的是对的，那就比较奇怪了，应该还是你ip的问题。 访问这个网站看看你香港的ip是不是真的在香港 [https://ipinfo.io/，如果真的是香港，那就可能是ip被ban了吧，换其他的ip](https://ipinfo.io/%EF%BC%8C%E5%A6%82%E6%9E%9C%E7%9C%9F%E7%9A%84%E6%98%AF%E9%A6%99%E6%B8%AF%EF%BC%8C%E9%82%A3%E5%B0%B1%E5%8F%AF%E8%83%BD%E6%98%AFip%E8%A2%ABban%E4%BA%86%E5%90%A7%EF%BC%8C%E6%8D%A2%E5%85%B6%E4%BB%96%E7%9A%84ip)
> > > > 
> > > > 
> > > > 刚看了下，香港的代理过期了，有那个域名能用美国ip访问吗
> > > 
> > > 
> > > 参考GitHub Actions的配置 [option_workflow_download.yml](https://github.com/hect0x7/JMComic-Crawler-Python/blob/master/assets/config/option_workflow_download.yml)
> > 
> > 
> > 意思是用action在线下载吗？刚试了下下载的图片默认是webp的，在哪个地方设置action 的下载格式呢
> 
> 不是，是参考actions的配置文件🤣 option_workflow_download.yml 在哪个地方设置action 的下载格式 -> 也是改actions的配置文件

本地没香港的代理的话，是不是只能用github action的方式下载了

**Comment by hect0x7** [comment]
你好像还是没懂我意思。
你可以使用美国代理+配置域名，域名配置就copy这里的代码
https://github.com/hect0x7/JMComic-Crawler-Python/blob/master/assets/config/option_workflow_download.yml#L10

**Comment by pannifeng** [comment]
> 你好像还是没懂我意思。 你可以使用美国代理+配置域名，域名配置就copy这里的代码 https://github.com/hect0x7/JMComic-Crawler-Python/blob/master/assets/config/option_workflow_download.yml#L10
python一窍不通，就是把 - jmcomic1.me  - jmcomic.me这两个域名扔到配置文件的client.domain下面吗

**Comment by pannifeng** [comment]
> 你好像还是没懂我意思。 你可以使用美国代理+配置域名，域名配置就copy这里的代码 https://github.com/hect0x7/JMComic-Crawler-Python/blob/master/assets/config/option_workflow_download.yml#L10

感谢楼主，配置域名之后解决了
