### ISSUE TITLE
【代码优化？】来自@coderabbitai

### ISSUE THREAD

**Issue by buiawpkgew1** [hect0x7/JMComic-Crawler-Python#158]
https://github.com/buiawpkgew1e/JMComic-Crawler-Python/pull/14#pullrequestreview-1703217468

**Comment by hect0x7** [comment]
好腻害的ai，不过仔细读了一下，感觉ai的全局联系能力还不太行，有些问题明显是只根据上下文提出来的，略显草率。

但有几点是可以改进下：
插件的入参校验问题，要不要抛异常？
zip插件在删除文件和文件夹时，增加一次判空校验。

**Comment by hect0x7** [comment]
插件的入参校验，不抛异常主要是为了兼容一种情况：用户配置了插件，但是没有配置核心参数。
就比如，用户配置了插件，插件里用到了一个环境变量，可能过了一段时间这个环境变量不在了。
那么这时插件是选择【空参不执行】好，还是【空参就报错】好？

我打算增加一个异常和配置项，当这个配置项开启时，【空参就报错】，否则使用【空参不执行】。
具体实现思路：由插件专门抛出这个异常，由option catch并根据配置项进行处理或丢弃。
