### ISSUE TITLE
在python上运行失败

### ISSUE THREAD

**Issue by zursoe** [hect0x7/JMComic-Crawler-Python#188]
我是小白，在vs上运行python，pip安装后，昨天下载还正常，无论是album还是photo都下载正常，今天突然不行了
代码是
`import jmcomic
jmcomic.download_photo('519829')
#下载章节

jmcomic.download_album('519829')
#下载全本`

错误提示是
`Message=partially initialized module 'jmcomic' has no attribute 'download_photo' (most likely due to a circular import)
AttributeError: partially initialized module 'jmcomic' has no attribute 'download_photo' (most likely due to a circular import)`

**Comment by hect0x7** [comment]
先试着更新jmcomic试试
```sh
pip install jmcomic -i https://pypi.org/project --upgrade
```

**Comment by zursoe** [comment]
> 先试着更新jmcomic试试
> 
> ```shell
> pip install jmcomic -i https://pypi.org/project --upgrade
> ```

不行，更新到2.4.13还是这个错误

**Comment by hect0x7** [comment]
可能是你运行环境的问题。正常使用步骤应该是：
1. 到python官网安装python（https://www.python.org/）
2. pip安装jmcomic

你所说的 在vs上运行python，是步骤1吗？

**Comment by zursoe** [comment]
> 可能是你运行环境的问题。正常使用步骤应该是：
> 
> 1. 到python官网安装python（https://www.python.org/ ）
> 2. pip安装jmcomic
> 
> 你所说的 在vs上运行python，是步骤1吗？

![1](https://github.com/hect0x7/JMComic-Crawler-Python/assets/143069840/fb6436f2-5dfd-4a5c-aa09-c23d4bd310d2)
如图所示，左边环境里我已经安装了最新的jmcomic，底下输出栏显示了错误原因。

**Comment by hect0x7** [comment]
> > 可能是你运行环境的问题。正常使用步骤应该是：
> > 
> > 1. 到python官网安装python（https://www.python.org/ ）
> > 2. pip安装jmcomic
> > 
> > 你所说的 在vs上运行python，是步骤1吗？
> 
> ![1](https://private-user-images.githubusercontent.com/143069840/294425372-fb6436f2-5dfd-4a5c-aa09-c23d4bd310d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDA5NTksIm5iZiI6MTcwNDQ0MDY1OSwicGF0aCI6Ii8xNDMwNjk4NDAvMjk0NDI1MzcyLWZiNjQzNmYyLTVkZmQtNGE1Yy1hYTA5LWMyM2Q0YmQzMTBkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwNzQ0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2FmNWQ1ZTJlY2IzZWU3Y2IyM2ViY2EyOWEzMTBlZWI4MzZmMmMzMjczY2FiN2YzMGQyYzA4ZTcyNTIwOWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d5nkubzdbBpJCtr1-HQ7dAHKx-J1uJ6kJiHDx1l_GRs) 如图所示，左边环境里我已经安装了最新的jmcomic，底下输出栏显示了错误原因。

啊我知道了，你python文件的命名不要命名成jmcomic.py，否则import jmcomic 会import你自己

**Comment by zursoe** [comment]
> > > 可能是你运行环境的问题。正常使用步骤应该是：
> > > 
> > > 1. 到python官网安装python（https://www.python.org/ ）
> > > 2. pip安装jmcomic
> > > 
> > > 你所说的 在vs上运行python，是步骤1吗？
> > 
> > 
> > ![1](https://private-user-images.githubusercontent.com/143069840/294425372-fb6436f2-5dfd-4a5c-aa09-c23d4bd310d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDA5NTksIm5iZiI6MTcwNDQ0MDY1OSwicGF0aCI6Ii8xNDMwNjk4NDAvMjk0NDI1MzcyLWZiNjQzNmYyLTVkZmQtNGE1Yy1hYTA5LWMyM2Q0YmQzMTBkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwNzQ0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2FmNWQ1ZTJlY2IzZWU3Y2IyM2ViY2EyOWEzMTBlZWI4MzZmMmMzMjczY2FiN2YzMGQyYzA4ZTcyNTIwOWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d5nkubzdbBpJCtr1-HQ7dAHKx-J1uJ6kJiHDx1l_GRs) 如图所示，左边环境里我已经安装了最新的jmcomic，底下输出栏显示了错误原因。
> 
> 啊我知道了，你python文件的命名不要命名成jmcomic.py，否则import jmcomic 会import你自己

太感谢了！！！
