### ISSUE TITLE
question

### ISSUE THREAD

**Issue by WangAYi** [hect0x7/JMComic-Crawler-Python#2]
您好，您是不是忘记上传一些文件了？我运行了代码发现里面有些类没被定义，像是这个SaveableEntity，IterableEntity。还有一些别的东西也不全，希望您可以回复我一些

**Comment by hect0x7** [comment]
是的，有一些内容这个仓库中没有。
你指的这些都是common模块的内容，在这个仓库：https://github.com/hect0x7/common
common模块是个人自用的一个模块，我本地的很多项目都使用到了它，jmcomic模块也不例外。
因此需要麻烦你先安装common模块，再安装jmcomic模块，然后就可以使用了。（使用pip install -e本地安装即可）

**Comment by WangAYi** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    首先谢谢您的解答，然后我在使用common模块时又发现了一些对象没有被定义的问题，希望您可以抽空解答我的问题
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                487617328
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 3/16/2023 ***@***.***> wrote： 



是的，有一些内容这个仓库中没有。
你指的这些都是common模块的内容，在这个仓库：https://github.com/hect0x7/common
common模块是个人自用的一个模块，我本地的很多项目都使用到了它，jmcomic模块也不例外。
因此需要麻烦你先安装common模块，再安装jmcomic模块，然后就可以使用了。（使用pip install -e本地安装即可）

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
