### ISSUE TITLE
请问有函数能只爬取漫画数据而不下载漫画吗？

### ISSUE THREAD

**Issue by Yunxi-awa** [hect0x7/JMComic-Crawler-Python#203]
期望功能如题。看了源代码，postman没有搞懂，只能过来提问了......

**Comment by hect0x7** [comment]
```python
from jmcomic import *

op = JmOption.default()
client = op.new_jm_client()
# 看看client有哪些方法就知道啦
```

**Comment by hect0x7** [comment]
也可以参考这个文档，里面有使用client的示例
https://jmcomic.readthedocs.io/en/latest/tutorial/3_demo/

**Comment by hect0x7** [comment]
其实downloader也是用get_photo_detail的，这个开销没法避免，因为禁漫只有在章节详情页会返章节图片数这一数据。

**Comment by Yunxi-awa** [comment]
> 其实downloader也是用get_photo_detail的，这个开销没法避免，因为禁漫只有在章节详情页会返章节图片数这一数据。

OK，妥协了

**Comment by Yunxi-awa** [comment]
> 其实downloader也是用get_photo_detail的，这个开销没法避免，因为禁漫只有在章节详情页会返章节图片数这一数据。

还有一个疑问，能不获取数据而只下载漫画吗🤔

**Comment by hect0x7** [comment]
> > 其实downloader也是用get_photo_detail的，这个开销没法避免，因为禁漫只有在章节详情页会返章节图片数这一数据。
> 
> 还有一个疑问，能不获取数据而只下载漫画吗🤔

扫图片cdn。因为图片url有规律，理论上可能还真行。

**Comment by hect0x7** [comment]
> > > 其实downloader也是用get_photo_detail的，这个开销没法避免，因为禁漫只有在章节详情页会返章节图片数这一数据。
> > 
> > 
> > 还有一个疑问，能不获取数据而只下载漫画吗🤔
> 
> 扫图片cdn。因为图片url有规律，理论上可能还真行。

但图片有混淆，要获取到scramble_id才能解密。不过scramble_id也有一定规律...🤣

**Comment by Yunxi-awa** [comment]
> > > > 其实downloader也是用get_photo_detail的，这个开销没法避免，因为禁漫只有在章节详情页会返章节图片数这一数据。
> > > 
> > > 
> > > 还有一个疑问，能不获取数据而只下载漫画吗🤔
> > 
> > 
> > 扫图片cdn。因为图片url有规律，理论上可能还真行。
> 
> 但图片有混淆，要获取到scramble_id才能解密。不过scramble_id也有一定规律...🤣

那就等着大佬继续更新了！🙏

**Comment by hect0x7** [comment]
我其实没有什么要更新的了，下载+本地离线浏览插件 已经能满足我个人的需求了😇

**Comment by Yunxi-awa** [comment]
> 我其实没有什么要更新的了，下载+本地离线浏览插件 已经能满足我个人的需求了😇

我这个项目做完了会开源，到时候如果你愿意的话这个项目也可以和jmcomic合并（三十年河东，三十年河西
