### ISSUE TITLE
BUG：APP_VERSION 应更新为 1.6.5

### ISSUE THREAD

**Issue by Yunxi-awa** [hect0x7/JMComic-Crawler-Python#204]
我记得有自动获取最新版本的功能来着

**Comment by hect0x7** [comment]
最新版本号是v1.6.6了
jmcomic是有api可以获取禁漫最新的app版本号。
对此我还专门开了个项目，定时检查禁漫app有没有更新：https://github.com/hect0x7/JMComic-APK
你可以参考这个项目的代码～也是调用client的方法

**Comment by hect0x7** [comment]
噢对，没回答你标题来着。
这个APP_VERSION是用在JmApiClient请求禁漫app接口时携带的参数。从经验来说，这个APP_VERSION不更新到最新也没事。一般如果更新都是因为禁漫接口调整了，低版本的APP_VERSION不能用了，才去更新APP_VERSION。

不过我也留了一个开关，使用下面的代码，可以自动使用最新的APP_VERSION进行请求。
```python
from jmcomic import JmModuleConfig
JmModuleConfig.flag_use_version_newer_if_behind = True
```
