### ISSUE TITLE
如何获取Album的大标签，如同人、韩漫、3D这种

### ISSUE THREAD

**Issue by Yunxi-awa** [hect0x7/JMComic-Crawler-Python#205]
如题，只看到config有定义，没看到接口🤔

**Comment by hect0x7** [comment]
这个属性实体类里是没有的，暂时获取不了。
如果要获取的话，网页端可以加个正则表达式，但APP端接口没有返这个字段，所以这又是一个没法统一的字段。
config确实有定义，主要是用在分类排行方法的参数，例如：
```python
from jmcomic import *

op = JmOption.default()
cl = op.new_jm_client()

# 获取周排行，类别选择韩漫（CATEGORY_HANMAN）
page = cl.week_ranking(page=1,
                       category=JmMagicConstants.CATEGORY_HANMAN,
                       )

for aid, atitle in page:
    print(aid, atitle)


```

**Comment by Yunxi-awa** [comment]
![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/130226803/f9f645b4-764a-4c1a-ab84-69d0d65a4797)
我看到搜索结果是有右上角的角标的，可以为JmSearchPage添加一个category的属性来获取大标签吗

**Comment by hect0x7** [comment]
可以加，但感觉意义不大，加可以加到JmSearchPage.content[album_id]的dict里。
另外，APP端的search接口倒是有返category这个字段：
```python
from jmcomic import *

op = JmOption.default()
cl = op.new_jm_client(impl='api')

page = cl.search_site('无修正')
for aid, aextra in page.iter_id_extra():
    print(aid, aextra['category']['title'])

```

**Comment by hect0x7** [comment]
可以加，但感觉意义不大。另外其实APP端的search接口是有返回category这个字段的。
```python
from jmcomic import *

op = JmOption.default()
cl = op.new_jm_client(impl='api')

page = cl.search_site('无修正')
for aid, ainfo in page.content:
    print(aid, ainfo['category']['title'])

"""
535012 同人
535020 同人
535028 同人
535045 同人
534968 其他類
526005 單本
378630 單本
"""
```

**Comment by hect0x7** [comment]
可以加，但感觉意义不大。另外其实APP端的search接口是有返回category这个字段的。
```python
from jmcomic import *

op = JmOption.default()
cl = op.new_jm_client(impl='api')

page = cl.search_site('无修正')
for aid, ainfo in page.content:
    print(aid, ainfo['category']['title'])

"""
535012 同人
535020 同人
535028 同人
535045 同人
534968 其他類
526005 單本
378630 單本
"""
```

**Comment by Yunxi-awa** [comment]
> 可以加，但感觉意义不大。另外其实APP端的search接口是有返回类别这个字段的。
> 
> ```python
> from jmcomic import *
> 
> op = JmOption.default()
> cl = op.new_jm_client(impl='api')
> 
> page = cl.search_site('无修正')
> for aid, ainfo in page.content:
>     print(aid, ainfo['category']['title'])
> 
> """
> 535012 同人
> 535020 同人
> 535028 同人
> 535045 同人
> 534968 其他類
> 526005 單本
> 378630 單本
> """
> ```

感谢大佬🙏

**Comment by Yunxi-awa** [comment]
```
    def parse_api_to_search_page(cls, data: DictModel) -> JmSearchPage:
        """
        model_data: {
          "search_query": "MANA",
          "total": "177",
          "content": [
            {
              "id": "441923",
              "author": "MANA",
              "description": "",
              "name": "[MANA] 神里绫华5",
              "image": "",
              "category": {
                "id": "1",
                "title": "同人"
              },
              "category_sub": {
                "id": "1",
                "title": "同人"
              }
            }
          ]
        }
        """
        total: int = int(data.total or 0)  # 2024.1.5 data.total可能为None
        content = cls.adapt_content(data.content)
        return JmSearchPage(content, total)
```
这里的categoriy和category_sub有什么区别？

**Comment by hect0x7** [comment]
> ```
> 
>     def parse_api_to_search_page(cls, data: DictModel) -> JmSearchPage:
> 
>         """
> 
>         model_data: {
> 
>           "search_query": "MANA",
> 
>           "total": "177",
> 
>           "content": [
> 
>             {
> 
>               "id": "441923",
> 
>               "author": "MANA",
> 
>               "description": "",
> 
>               "name": "[MANA] 神里绫华5",
> 
>               "image": "",
> 
>               "category": {
> 
>                 "id": "1",
> 
>                 "title": "同人"
> 
>               },
> 
>               "category_sub": {
> 
>                 "id": "1",
> 
>                 "title": "同人"
> 
>               }
> 
>             }
> 
>           ]
> 
>         }
> 
>         """
> 
>         total: int = int(data.total or 0)  # 2024.1.5 data.total可能为None
> 
>         content = cls.adapt_content(data.content)
> 
>         return JmSearchPage(content, total)
> 
> ```
> 
> 这里的categoriy和category_sub有什么区别？

问得好，其实我也不知道🤣

**Comment by Yunxi-awa** [comment]
`{'id': '19', 'author': '渚ミナミ', 'description': None, 'name': '[渚ミナミ] 怪盗熟女クロアゲハ', 'image': '', 'category': {'id': '2', 'title': '单本'}, 'category_sub': {'id': '5', 'title': '韩漫'}, 'liked': False, 'is_favorite': False, 'tags': []}`
这是程序运行中debug的输出，明显发现category_sub的id为5与19大相径庭。
