### ISSUE TITLE
关于命名规则的问题：能否在命名时加入tag以方便本地管理

### ISSUE THREAD

**Issue by xiank1** [hect0x7/JMComic-Crawler-Python#220]

**Comment by hect0x7** [comment]
rule是支持引用tag的，JmAlbumDetail和JmPhotoDetail都有一个tags字段表示所有的标签。
然后rule也是支持引用`自定义字段`的，如果你会写代码的话，可以自己处理tags字段然后放入命名中。参考文档→ [自定义下载文件夹名](https://github.com/hect0x7/JMComic-Crawler-Python/blob/master/assets/docs/sources/tutorial/9_custom_download_dir_name.md)

**Comment by xiank1** [comment]
十分感谢，已经解决了
