### ISSUE TITLE
下載多話的漫畫資料夾名稱問題

### ISSUE THREAD

**Issue by Chia-0918** [hect0x7/JMComic-Crawler-Python#240]
有社團學姐為例：
這是網頁上的話數，可以看到每一個都有標示第幾話
![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/62283981/ad9b6f8a-05d9-47a7-b482-998e7f81cbeb)

但我使用jmcomic.download_album('570311')下載時，下載下來有些資料夾沒有標記第幾話，如下圖：
![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/62283981/ec017cd0-4b54-43b2-854a-e7aaf819c721)

這對我要完全自動化會有點難度
請問這該如何解決？謝謝！

**Comment by hect0x7** [comment]
这是个文件夹命名规则问题，你配置option来解决：
```yml
dir_rule:
  rule: Bd / Pindextitle # indextitle 会带上第几话
```

不清楚的地方请参考文档→ https://jmcomic.readthedocs.io/en/latest/tutorial/9_custom_download_dir_name/

**Comment by Chia-0918** [comment]
謝了 老哥
