### ISSUE TITLE
最新GitHub Actions 无法下载文件

### ISSUE THREAD

**Issue by lhcsas** [hect0x7/JMComic-Crawler-Python#243]
![Snipaste_2024-05-19_13-28-30](https://github.com/hect0x7/JMComic-Crawler-Python/assets/111757155/ca7dd459-0189-4d7f-9dab-418a7d6c7613)

**Comment by hect0x7** [comment]
请提供URL，以及你的操作

**Comment by lhcsas** [comment]
Artifact download URL: https://github.com/lhcsas/JMComic-Crawler-Python/actions/runs/9144848559/artifacts/1516512594

**Comment by lhcsas** [comment]
![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/111757155/5dcbe215-953a-4612-8e86-110933c2a352)
本子是下载好了，就是点下载那个会出现xml错误，下载的时候我只输入了本子的id

**Comment by lhcsas** [comment]
![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/111757155/11103fca-aba1-461d-b927-12bf76f30402)
我只填了本子的id，下面的我都没填

**Comment by hect0x7** [comment]
操作是对的，看起来是github的问题，之前没出现过这个错

**Comment by hect0x7** [comment]
把上传文件名称改成非中文试试：https://github.com/hect0x7/JMComic-Crawler-Python/actions/runs/9145470679

**Comment by lhcsas** [comment]
可以下载了，感谢
