### ISSUE TITLE
对于多章节漫画只能下载第一章

### ISSUE THREAD

**Issue by yubinquankuang** [hect0x7/JMComic-Crawler-Python#262]
多章节漫画，只下载第一章

**Comment by hect0x7** [comment]
请提供本子id，并自行测试非第一章的章节是否免登录观看，如有问题可在重新打开issue

**Comment by yubinquankuang** [comment]
id：209827
是可以不登陆看其他章节的
https://18comic-deadp.org/album/209827

**Comment by hect0x7** [comment]
提供一下你的代码？

**Comment by hect0x7** [comment]
我试了是可以下载所有章节的

**Comment by yubinquankuang** [comment]
option = jmcomic.create_option(option_file)
jmcomic.download_album(209827,option)

option：
client:
  cache: true
  domain:
      - 18comic-deadp.org
  impl: html
  postman:
    meta_data:
      headers: null
      impersonate: chrome110
      proxies: {}
      cookies:
        AVS: uigusig8fgjcj6l4dgmvml9b20 # 这个值是乱打
    type: cffi
  retry_times: 5
dir_rule:
  base_dir: D:\project\hanman
  rule: Bd_Atitle_Pindex
download:
  cache: true
  image:
    decode: true
    suffix: null
  threading:
    image: 30
    photo: 8
log: true

**Comment by hect0x7** [comment]
你把domain配置项去掉试试

**Comment by hect0x7** [comment]
或者使用18comic.vip
再或者换impl: api试试
