### ISSUE TITLE
按照作者名搜索，搜索失败

### ISSUE THREAD

**Issue by heathhou** [hect0x7/JMComic-Crawler-Python#264]
我试了下代码中的搜索，使用站内搜索（search_site）正常，但是我想按照作者名来搜索，使用search_author，搜出来的作品都为空，即搜不出来作品，不管使用哪一个作者名都是这样。请问是我没有正常使用还是这个功能没有实现啊？

**Comment by hect0x7** [comment]
贴一下你的代码。
你运行时应该有日志输出吧？访问一下看看网页是不是确实没结果
