### ISSUE TITLE
[Help] 使用插件怎么获取指定本子的页数和上架时间

### ISSUE THREAD

**Issue by preBall** [hect0x7/JMComic-Crawler-Python#276]
### 注意事项

- [X] 提ISSUE前，请确认你已经在GitHub Issues和Discussions里搜索过类似的问题，并且没找到想要的答案。

### 你使用的是哪种方式？

Python代码

### 你的目的？

我想知道可以通过本子实体类或者其它方法获取某个指定本子页数和上架时间吗？

### 你遇到的困难？

翻阅文档后发现使用本子实体类获取的属性有page_num,但是测试后发现请求出来的本子的某几个属性一直为0，不知道是我的代码写的有问题还是目前库中获取的数据有问题下面是我写的代码和获取的数据
![image](https://github.com/user-attachments/assets/bc96ca5c-5b5b-4e7e-b85e-369df22b73c1)

**Comment by hect0x7** [comment]
禁漫APP端不返回总页数，你需要切换到网页端来获取这一字段，即配置impl： html

**Comment by hect0x7** [comment]
你可以在代码第4行加一个参数impl=html
