### ISSUE TITLE
下载本集子同名章节写入时会反复覆盖

### ISSUE THREAD

**Issue by kkAct** [hect0x7/JMComic-Crawler-Python#29]
<img width="755" alt="image" src="https://github.com/hect0x7/JMComic-Crawler-Python/assets/41529707/a7f19bc0-e21e-4f41-adb3-b5a3df2acbd2">
建议给每个章节新增一个photo id

**Comment by hect0x7** [comment]
同名章节确实会有这样的问题。
解决方式是：
1. 换一个DownloadDirTree的flag，如 `Bd_Id_Index_image`: 根目录 / AlbumId / Photo序号 / 图片文件
2. 自行定制本子的下载路径，代码参考 https://github.com/hect0x7/JMComic-Crawler-Python/issues/8

另外我打算把本仓库的配置文件里的flag改成 `Bd_Id_Index_image`，避免小白出现问题

**Comment by hect0x7** [comment]
也许应该实现一种更灵活的dsl，可以把形如 `Bd_Aauthor_Atitle_Pindex_image` 的flag自动解析为 `根目录 / Album作者 / Album标题 / Photo序号 / 图片文件` 这种规则

**Comment by hect0x7** [comment]
> 也许应该实现一种更灵活的dsl，可以把形如 `Bd_Aauthor_Atitle_Pindex_image` 的flag自动解析为 `根目录 / Album作者 / Album标题 / Photo序号 / 图片文件` 这种规则

该功能已实现，代码在dev_2.0分支的DirRule

**Comment by hect0x7** [comment]
发布了v2.0.0，你可以使用这样的配置区分不同章节：
```yml
dir_rule:
  base_dir: 根目录
  rule: Bd_Atitle_Pindex # 根目录 / 本子标题 / 章节序号 / 图片文件
```
如果你还有问题，可以提在这个issue下面或者新开issue
