### ISSUE TITLE
[Bug] 2024年10月9日无法使用脚本， 能够正常访问到页面，

### ISSUE THREAD

**Issue by goubo** [hect0x7/JMComic-Crawler-Python#290]
### 注意事项

- [X] 提ISSUE前，请确认你已经在GitHub Issues和Discussions里搜索过类似的问题，并且没找到想要的答案。
- [X] GitHub Actions问题请到置顶的Issue反馈。

### 发生Bug时，你的使用方式？

jmcomic命令行

### 你是否在禁漫官方网页或APP，验证过相应的功能是正常的？

测试过，禁漫官方功能正常

### option配置+源码/命令

`jmcomic 123 `

### 你预期的结果，与实际结果的差别

默认进行了5次重试，日志中打印出完整的页面html内容，但是抛出jmcomic.jm_exception.RequestRetryAllFailException: 请求重试全部失败，
命令行和脚本都测试过，使用api地址登录也会报错，使用html模式，能够登录和获取详情，后面仍会报错

**Comment by hect0x7** [comment]
报错的日志贴一下

**Comment by goubo** [comment]
position: relative;
}
</style>
<script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="152c4d6d44877cb55f0bfee6-|49" defer></script><script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML="window.__CF$cv$params={r:'8cfe0978bdec04c5',t:'MTcyODQ3MzQwOS4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body>
</html>
]
[2024-10-09 19:30:10] [MainThread]:【api】https://www.jmapiproxyxxx.one/setting
[2024-10-09 19:30:10] [MainThread]:【req.retry】次数: [0/1], 域名: [2 of ['www.jmeadpoolcdn.life', 'www.jmeadpoolcdn.one', 'www.jmapiproxyxxx.one']], 路径: [https://www.jmapiproxyxxx.one/setting], 参数: [{'headers': {'Accept-Encoding': 'gzip, deflate', 'user-agent': 'Mozilla/5.0 (Linux; Android 9; V1938CT Build/PQ3A.190705.11211812; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Safari/537.36', 'token': 'cd59d23e0d23f6fb90f6b86dc34343eb', 'tokenparam': '1728473404,1.7.2'}}]
[2024-10-09 19:30:12] [MainThread]:【req.error】请求不是json格式，强制重试！响应文本: [<!doctype html>
<html lang="en">
<head>
<meta name="google" content="notranslate">
<meta name="juicyads-site-verification" content="9dc45d0c989efd2d562bc0bfa0ae960b">
<meta name="exoclick-site-verification" content="02a42f90b0f54accd3b5a8b44e3c2c54">
<meta name="trafficjunky-site-verification" content="vtt10qy00" />
<meta name="ero_verify" content="c55bde9f8536c9020bbbdee53a9ceee9" />
<meta name="linkbuxverifycode" content="32dc01246faccb7f5b3cad5016dd5033" />
日志包含整个页面的html，内容非常大。这是使用脚本时重试之间答打印的提示，附件为使用jmcomic 123 命令的完整输出。
[err.log](https://github.com/user-attachments/files/17307306/err.log)

**Comment by hect0x7** [comment]
这个报错是因为这个域名被重定向到网页了，可能是这个域名不可用了，得换别的移动端域名

**Comment by hect0x7** [comment]
已修复api，更新jmcomic到最新版即可。
html版应该不受影响，我测试了没问题。

**Comment by goubo** [comment]
大佬好棒，html的客户端返回的机构体略有不同，应该是我脚本的问题
