### ISSUE TITLE
无法获取多页图片数据

### ISSUE THREAD

**Issue by kkAct** [hect0x7/JMComic-Crawler-Python#3]
bug：

当单章节图片超过300张的时候，无法获取第二页第三页的数据

需要修改get_photo_detail方法

**Comment by kkAct** [comment]
刚刚去看了一下页面，可以解析一下第一页底部的class="pagination"的分页器 ,增加query_params ?page={page}参数获取

**Comment by hect0x7** [comment]
我发现页面的js里有个page_arr变量记录了所有图片的图片名，所以我打算用模版方式生成图片的URL。
例如，图片URL为`https://cdn-msp2.18comic.org/media/photos/147643/00001.webp`：
1. 解析出域名`cdn-msp2.18comic.org` as `data_original_domain`
2. 根据index从page_arr中拿图片名 `page_arr[index]` as `img_name`
3. 有了data_original_domain和img_name，生成图片URL `https://{data_original_domain}/media/photo/{img_name}`

**Comment by hect0x7** [comment]
已实现解析全部页数的功能，详见提交：https://github.com/hect0x7/JMComic-Crawler-Python/commit/47d78cafb630882e24166667c1a7540d6f65905c
