### ISSUE TITLE
本地部署如何设置代理访问

### ISSUE THREAD

**Issue by AntaresD** [hect0x7/JMComic-Crawler-Python#300]
### 注意事项

- [X] 提ISSUE前，请确认你已经在GitHub Issues和Discussions里搜索过类似的问题，并且没找到想要的答案。

### 你使用的是哪种方式？

jmcomic命令行

### 你遇到的困难？

![001](https://github.com/user-attachments/assets/3bb0058d-0afa-42c6-9ce5-ec37862ec398)
![002](https://github.com/user-attachments/assets/cae4efef-c3cd-4c87-981d-530fa0b2c6da)
大佬，您好，我用的是clash for windows，已经开启系统代理，但还是无法访问，想请问下，proxies:应该如何配置？

**Comment by hect0x7** [comment]
这个报错是你yml格式有误，AVS冒号后面少了个空格

**Comment by hect0x7** [comment]
代理配置是对的

**Comment by AntaresD** [comment]
> 报这个错误是你yml格式有错误，AVS冒号后面少了个空格

![001](https://github.com/user-attachments/assets/42386fb4-36d9-403f-8146-2712ae65a247)
![002](https://github.com/user-attachments/assets/1e0c4efa-271f-4163-90d1-c0bc359e018a)
嗯嗯，请问我哪里还需要改进嘛？

**Comment by hect0x7** [comment]
domain配置的有问题，你配了个网页端域名，但是impl写了api。
把impl改成html，或者domain移除掉。

**Comment by AntaresD** [comment]
成功啦，谢谢大佬！

**Comment by AntaresD** [comment]
> domain配置的有问题，你配了个网页端域名，但是impl写了api。 把impl改成html，或者domain移除掉。

成功啦，谢谢大佬！0.o
