### ISSUE TITLE
[Feature] 希望增加搜索返回image地址

### ISSUE THREAD

**Issue by bilili-syy** [hect0x7/JMComic-Crawler-Python#311]
### 新功能请求

搜索返回我发现image字段是空的。

**Comment by hect0x7** [comment]
你说的image是啥？
你有试过官方功能是否支持吗？

**Comment by hect0x7** [comment]
APP的搜索API返回的image就是空的，获取图片是直接访问url：
https://cdn-msp3.jmapiproxy1.cc/media/albums/{album_id}_3x4.jpg?v=1732172548

**Comment by bilili-syy** [comment]
> APP的搜索API返回的image就是空的，获取图片是直接访问url： [https://cdn-msp3.jmapiproxy1.cc/media/albums/{album_id}_3x4.jpg?v=1732172548](https://cdn-msp3.jmapiproxy1.cc/media/albums/%7Balbum_id%7D_3x4.jpg?v=1732172548)

懂了懂了谢谢大佬
