### ISSUE TITLE
[Bug] 漫画标题本身出现未闭合的括号引起报错

### ISSUE THREAD

**Issue by wushixiaoyou** [hect0x7/JMComic-Crawler-Python#316]
### 注意事项

- [X] 提ISSUE前，请确认你已经在GitHub Issues和Discussions里搜索过类似的问题，并且没找到想要的答案。
- [X] GitHub Actions问题请到置顶的Issue反馈。

### 发生Bug时，你的使用方式？

Python代码

### 你是否在禁漫官方网页或APP，验证过相应的功能是正常的？

我要反馈的bug无需验证/不方便验证

### option配置+源码/命令

jm152353  
[月光石汉化] [ほとりぼっち (桜去ほとり)] 正妻力の高い7つ下の妹と既成事実をつくる本 [
jm_tooltik.py - class JmcomicText: - def tokenize(cls, title: str) -> List[str]: 
Core.src.jmcomic.jm_exception.JmcomicException: 未闭合的 []: [

第一次使用github提交issue 如有不合理或者描述不准确的地方请谅解

### 其他信息

        while i < length:
            c = title[i]

            if c in bracket_map:
                # 上一个单词结束
                add()
                # 定位右括号
                j = find_right_pair(c, i)
                if j == -1 :#目前因为我自己也修改了文件夹名称部分 使用的 作者\jm号\章节序号 的格式  所以在这里添加了这几段内容来跳过这个判定,应该对我自己不会有什么影响
                    title = title + bracket_map[c]
                    j = length
                #ExceptionTool.require_true(j != -1, f'未闭合的 {c}{bracket_map[c]}: {title[i:]}')
                # 整个括号的单词结束
                add(title[i:j])
                # 移动指针
                i = j
            else:
                char_list.append(c)
                i += 1

**Comment by hect0x7** [comment]
感谢反馈，这里改法挺多的，我倾向于这么改，都行
```python
        while i < length:
            c = title[i]

            if c in bracket_map:
                # 上一个单词结束
                add()
                # 定位右括号
                j = find_right_pair(c, i)
                if j == -1:
                    # 括号未闭合
                    char_list.append(c)
                    i += 1
                    continue
                # 整个括号的单词结束
                add(title[i:j])
                # 移动指针
                i = j
            else:
                char_list.append(c)
                i += 1

```

**Comment by hect0x7** [comment]
最新版本已修复，未闭合不会引起报错

**Comment by wushixiaoyou** [comment]
还有两个小问题请问一下   
1 下载时即使只使用一个线程  (配置文件:download:  threading:    image: 20    photo: 1 ) 的时候cpu占用也非常高 (13900K) 看vscod的调用栈堆依然会有很多 这个是因为那个image20的原因吗   不知道和cpu单核使用量有没有什么影响    有什么降低一些的办法吗   我的目标是作为一个循环访问收藏夹如果收藏夹有变化就下载的长期后台 下图速度降低是可以接受的(目前情况 photo:8  一开始下载起来直接吃100%风扇转速都拉满了其他什么事都干不了)
2 有什么办法可以了解你们更新后的代码和我自己原来修改过的地方的区别嘛  还是说只能自己记录每次更新再自己改

**Comment by hect0x7** [comment]
1.你是同时下载多个本子吗？image和photo是每个本子的图片和章节并发数，如果你是一个本一个本下载，那压力应该不大才对。
注意download_album的传参是多个id和单个id，多个id会多线程同时下载本子。

2. jmcomic发布的代码都在master分支，看git提交改动点就行。
如果你想每次更新都保留自己的一些改动，建议别直接改你本地的jmcomic库代码，你应该在你的python代码开始运行一些覆盖jmcomic功能的代码，比如 Jmcomic.tokenize = my_tokenize

**Comment by wushixiaoyou** [comment]
1.我的方式是  从收藏夹获取jmid形成一个列表对比自己记录的已经下载过的jmid列表 取补集 然后用for jmid in 列表: 的形式  应该是一个本一个本的下的才对   那我应该吧image数量也降低一些是吗
2.这个办法好像有点超出我的能力  那就还是记录一下修改的位置每次更新后补上去好了
感谢解答

**Comment by hect0x7** [comment]
可以试下降低image看看，可以观察日志验证
