### ISSUE TITLE
为所有请求增加retry参数

### ISSUE THREAD

**Issue by kkAct** [hect0x7/JMComic-Crawler-Python#4]
每次下载都会有几张请求失败的图片，建议增加一个retry参数在配置项，对失败的请求进行重试次数

**Comment by hect0x7** [comment]
这确实是个比较大的问题，估计是禁漫的服务器压力比较大，图片数多+多线程就容易失败。刚刚提交了一个commit，就是关于重试机制。

**Comment by kkAct** [comment]
我尝试了一下，失败率低了很多，但还是会有，建议可以配置

**Comment by hect0x7** [comment]
可以配置的，配置项是client_config.retry_times

例如，yml的配置如下：
client_config:
  retry_times: 10 # 请求重试次数
  domain: jmcomic1.group
  # 省略剩下的配置项

**Comment by hect0x7** [comment]
可以配置的，配置项是client_config.retry_times

例如，yml的配置如下：
client_config:
retry_times: 10 # 请求重试次数
domain: jmcomic1.group
# 省略剩下的配置项

**Comment by hect0x7** [comment]
可以配置的，配置项是client_config.retry_times

例如，yml的配置如下：

client_config:
retry_times: 10 # 请求重试次数
domain: jmcomic1.group
 ... # 省略剩下的配置项

**Comment by kkAct** [comment]
perfect！
