### ISSUE TITLE
章节数获取错误

### ISSUE THREAD

**Issue by kkAct** [hect0x7/JMComic-Crawler-Python#41]
仅能获取到第一章

**Comment by hect0x7** [comment]
代码？

**Comment by kkAct** [comment]
pip安装
jmcomic.download_album()方法获取含有多章节的album时，只能读到第一个，试了几个都是这样

**Comment by hect0x7** [comment]
你应该使用的不是 18comic.* 这样到域名吧？

**Comment by kkAct** [comment]
我使用jmcomic.JmModuleConfig.get_jmcomic_url()获取到了这个域名
jm-comic2.cc
这个域名可以正常使用，使用18comic.vip无法访问，我开了全局代理并配置proxy: clash后得到403错误

**Comment by kkAct** [comment]
这是我的配置文件
client:
  domain: ["jm-comic2.cc"]
  impl: html
  postman:
    meta_data:
      cookies: null
      proxies: clash
      allow_redirects: true
      headers:
        accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        accept-language: zh-CN,zh;q=0.9
        authority: 18comic.vip
        sec-ch-ua: '"Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"'
        sec-ch-ua-mobile: ?0
        sec-ch-ua-platform: '"Windows"'
        sec-fetch-dest: document
        sec-fetch-mode: navigate
        sec-fetch-site: none
        sec-fetch-user: ?1
        upgrade-insecure-requests: '1'
        user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
          like Gecko) Chrome/111.0.0.0 Safari/537.36
      impersonate: chrome110
    type: cffi
  retry_times: 20
debug: true
dir_rule:
  base_dir: /Volumes/Media Library Private/comic
  rule: Bd_Ptitle
download:
  cache: true
  image:
    decode: true
    suffix: null
  threading:
    batch_count: 30
version: '2.0'

**Comment by hect0x7** [comment]
目前只能获取第一章的原因是，正则表达式不适配jm-comic2.cc和jm-comic.org这两个域名，解析出的本子的章节为空。
当本子的章节为空，会默认只有一章，因此只下载了一章。

**Comment by hect0x7** [comment]
我刚刚适配了下上面两个域名，准备发布，你可以稍后再试下，需要用pip更新jmcomic
对了，关于18comic.vip，你的配置没有问题，只是最近网站限制相当严，用浏览器访问也会抛403.
我想最根本的解决方案还是要上移动端api😥

**Comment by hect0x7** [comment]
已发布，实测 jm-comic2.cc 是可以下载到全部章节的

**Comment by kkAct** [comment]
在chrome可以正常访问的情况下，依旧出现403的情况

**Comment by hect0x7** [comment]
> 在chrome可以正常访问的情况下，依旧出现403的情况

我试了下确实。按以往经验大概率应该是headers的问题。你可以试下浏览器隐身模式f12抓包，然后在配置文件中配置你浏览器抓取的headers，应该就可以了。

**Comment by hect0x7** [comment]
实测应该只是加了 `referer` 字段校验
headers的配置里加上下面这行就行了。
```yml
referer: 'https://18comic.vip'
```
