### ISSUE TITLE
下载多章节类型的韩漫报错，提示Process completed with exit code 1.

### ISSUE THREAD

**Issue by CooperWen** [hect0x7/JMComic-Crawler-Python#43]
比如：
390371
323359

这个需要怎么解决呀

**Comment by CooperWen** [comment]
不对，试了一下是全都不行。
fork之后的操作方式和之前保持一样的，今天看到更新之后重新fork了一下就跑不动了

**Comment by hect0x7** [comment]
最近禁漫风控严，用github actions下载不了，跟漫画是多章节还是单章无关。

解决方案：
①如果你会python，本地安装+指定国内直连域名，目前还可以下载。
②如果你不会python，只能等禁漫降温，或者等我什么时候实现了移动端api😪

方案①，你可以参考：https://github.com/hect0x7/JMComic-Crawler-Python/issues/2 和 https://github.com/hect0x7/JMComic-Crawler-Python/issues/41

**Comment by CooperWen** [comment]
好的谢谢大佬

**Comment by hect0x7** [comment]
github actions 已可以使用
