### ISSUE TITLE
能使用list吗

### ISSUE THREAD

**Issue by buiawpkgew1** [hect0x7/JMComic-Crawler-Python#5]
比如
```python
import jmcomic
list=['xxx','xxx']
jmcomic.download_album(list)
```

**Comment by hect0x7** [comment]
目前没有这种list下载的api。不过这种调用方式，需要讨论的问题是，你期待的效果是【并行下载】还是【排队下载】？

我有时也要批量下载漫画，并且希望的是【并行下载】，因为这样最快。那我会使用如下代码，为每个album开一个线程去执行 `jmcomic.download_album`：
```python
import jmcomic
from common import str_to_list, multi_thread_launcher


album_id_ls: list[str] = str_to_list('''
297626
297627
2976
2999

''')

multi_thread_launcher(
    iter_objs=album_id_ls,
    apply_each_obj_func=jmcomic.download_album
)
```
如果你也想要【并行下载】，你可以参考上面的代码。而如果你想要【排队下载】，使用for循环即可。

不过总的来说来，我觉得也是值得加一个批量下载的方法的。我增加一下然后发布一个新版本吧~

**Comment by buiawpkgew1** [comment]
![image](https://user-images.githubusercontent.com/71136405/229264762-b36bc377-6703-4e99-8f28-245292529b47.png)
有时候是乱码

**Comment by hect0x7** [comment]
发布新版本v0.4.6，已增加批量下载api，支持list/set/tuple/迭代器/生成器等等类型。

**Comment by hect0x7** [comment]
> ![image](https://user-images.githubusercontent.com/71136405/229264762-b36bc377-6703-4e99-8f28-245292529b47.png) 有时候是乱码

我在linux上试了下这个album，没有问题，可能是你的服务器某些地方配置有问题？
![Snipaste_2023-04-01_12-36-24](https://user-images.githubusercontent.com/93357912/229265844-6599980c-ba19-4e3e-9b6c-841a9af2d7b0.png)

**Comment by hect0x7** [comment]
> ![image](https://user-images.githubusercontent.com/71136405/229264762-b36bc377-6703-4e99-8f28-245292529b47.png) 有时候是乱码

建议你可以新开一个issue，专门来讨论你的乱码问题。而这个issue如果你觉得没问题就可以close掉啦。

**Comment by buiawpkgew1** [comment]
> > ![image](https://user-images.githubusercontent.com/71136405/229264762-b36bc377-6703-4e99-8f28-245292529b47.png) 有时候是乱码
> 
> 我在linux上试了下这个album，没有问题，可能是你的服务器某些地方配置有问题？
> ![Snipaste_2023-04-01_12-36-24](https://user-images.githubusercontent.com/93357912/229265844-6599980c-ba19-4e3e-9b6c-841a9af2d7b0.png)
> 

这个是github 上的

**Comment by hect0x7** [comment]
> > > ![image](https://user-images.githubusercontent.com/71136405/229264762-b36bc377-6703-4e99-8f28-245292529b47.png) 有时候是乱码
> > 
> > 
> > 我在linux上试了下这个album，没有问题，可能是你的服务器某些地方配置有问题？
> > ![Snipaste_2023-04-01_12-36-24](https://user-images.githubusercontent.com/93357912/229265844-6599980c-ba19-4e3e-9b6c-841a9af2d7b0.png)
> 
> 这个是github 上的

重开一个issue讨论吧，正好我打算学习使用一下github action

**Comment by buiawpkgew1** [comment]
![image](https://user-images.githubusercontent.com/71136405/229327012-6684da09-2a98-42ba-896c-b12e57514797.png)

有时候是乱码的

**Comment by hect0x7** [comment]
上面输出有两类。
一类是异常，这类信息不能删，要留着排查问题。
一类是【xxx】xxxx的debug输出，可以删，把日志关掉就行了。

使用这行代码把debug日志关闭：
```python
JmModuleConfig.disable_jm_debug()
```

**Comment by hect0x7** [comment]
> ![image](https://user-images.githubusercontent.com/71136405/229327012-6684da09-2a98-42ba-896c-b12e57514797.png)
> 
> 有时候是乱码的

我无法复现这个问题，这是我最新跑的一次Github Actions，并没有乱码：https://github.com/hect0x7/JMComic-Crawler-Python/actions/runs/4586573986/jobs/8099514390
我增加了使用Github Actions和本项目API来下载禁漫本子的教程，你可以试着按教程重新来一遍，看看结果如何。
教程文档：https://github.com/hect0x7/JMComic-Crawler-Python/blob/main/assets/docs/%E6%95%99%E7%A8%8B%EF%BC%9A%E4%BD%BF%E7%94%A8Github%20Actions%E4%B8%8B%E8%BD%BD%E7%A6%81%E6%BC%AB%E6%9C%AC%E5%AD%90.md
