### ISSUE TITLE
使用安装了linux mint 的z8350小主机用docker安装jmcomic库下载本子列表导致内存爆满死机

### ISSUE THREAD

**Issue by Logan147** [hect0x7/JMComic-Crawler-Python#52]
使用安装了linux mint 的z8350小主机用docker安装jmcomic库下载本子列表导致内存爆满死机

我在docker容器里使用jmcomic的python库进行本子的爬取但是4G的运行内存没多久就满了然后就死机了
可以说一下这可能是什么问题吗，以及如何解决这个内存占用太大的问题？

**Comment by Logan147** [comment]
是这个cache配置项造成的吗

 },
  "download": {
    "cache": false,
    "image": {
      "decode": true,
      "suffix": ".jpg"

**Comment by Logan147** [comment]
我之前的配置是true我现在把它改成false试试

**Comment by Logan147** [comment]
好像就是这个的问题，现在htop的Mem显示只占用了1.67G

**Comment by Logan147** [comment]
问题又出现了，不是这个的问题，运存占用又变成了3G多！！！！

**Comment by hect0x7** [comment]
把你的完整配置发下，我猜大概率是 图片数太多 → 线程数爆炸 → 内存爆满，通过改配置能改善这个问题

**Comment by Logan147** [comment]
好了，我把batch_count改成8就好了
