### ISSUE TITLE
请问一下用config.yml应该如何设置自定义下载文件夹

### ISSUE THREAD

**Issue by pkr5277** [hect0x7/JMComic-Crawler-Python#56]
请问一下用config.yml应该如何设置自定义下载文件夹，自动把本子下载到对应的本子文件夹，而不是全都下载到主目录，还有如何批量下载多个本子？

**Comment by hect0x7** [comment]
配置文件的用法我已经写了一个蛮详细的介绍了，请看 `assets/config/常用配置介绍.yml`
如果你看不懂、或者不知道怎么写，你需要把你的预期效果详细写出来，我会考虑帮你写一下。

至于批量下载多个本子，请看 `usage`文件夹下的代码，有API快速上手介绍、示例、以及Github Actions工作流使用实例。
