### ISSUE TITLE
jm1，jm2,jm3,jm4，报错

### ISSUE THREAD

**Issue by kkurag** [hect0x7/JMComic-Crawler-Python#66]
我的python版本是3.10，
当我尝试直接输入1，2，3，4，不会发出请求
【api】https://18comic.vip/album/1
<img width="723" alt="image" src="https://github.com/hect0x7/JMComic-Crawler-Python/assets/111939763/e11765aa-c05d-4fd9-a49d-8f57a1a21051">
当我尝试输入jm1，jm2,jm3,jm4
能够正确返回，但没有进行下载图片，我自己调用对应的cdn地址是存在的图片的
<img width="846" alt="image" src="https://github.com/hect0x7/JMComic-Crawler-Python/assets/111939763/d322686f-6f23-48b5-b482-0f076fba8b4b">

**Comment by hect0x7** [comment]
已发布了v2.0.8，应该修复了这个问题，你可以试下

**Comment by kkurag** [comment]
> 已发布了v2.0.8，应该修复了这个问题，你可以试下

十分感谢，是成功修复了
