### ISSUE TITLE
建议添加在章节名称前加序号的下载方式，因为很多漫画的章节名称是无序的

### ISSUE THREAD

**Issue by tnxl** [hect0x7/JMComic-Crawler-Python#8]
建议添加在章节名称前加序号的下载方式，因为很多漫画的章节名称是无序的

<img width="1039" alt="Snipaste_2023-04-04_23-05-18" src="https://user-images.githubusercontent.com/31915062/229837576-049b2c12-13f9-4faa-8c36-592f70ee281d.png">

小白一个....我尝试在deside_image_save_dir中添加index形参，并将download_photo中的index数据一路传进去，但不知道是因为多线程还是其他原因，最后拼接出来的章节文件夹名称和序号是不对，查看yml配置文件也没有相关的配置，所以希望作者能添加该下载方式，最好是在目标位置先按照漫画名称创建文件夹后，再在里面按照序号创建章节文件夹，水平太差，在此请教作者。

**Comment by hect0x7** [comment]
谢谢你的建议~
首先，对于你的提议，我的理解应该属于【自定义下载路径】的需求。
【自定义下载路径】这个需求确实很常见，也很有必要支持。如何支持下载路径的自定义，不局限于几种特定的类型，也是我在不断考虑的点。为此我其实已经提供了一定的机制。

下面我向你演示，在不改变源代码的情况下，如何利用现有API提供的扩展机制，实现你的需求：【章节的下载文件夹的名称前加序号】

```python
from jmcomic import *

option = JmOption.default()


# 写一个自己的Advice，继承JmOptionAdvice，实现回调方法
class MyDownloadAdvice(JmOptionAdvice):

    # 我们只要定制图片下载文件夹，因此只需要实现这个decide_image_save_dir方法
    def decide_image_save_dir(self,
                              option: 'JmOption',
                              album_detail: Optional[JmAlbumDetail],
                              photo_detail: JmPhotoDetail,
                              ) -> StrNone:
        """
        决定一个本子图片的下载文件夹
        @param option: JmOption对象
        @param album_detail: 本子集实体类
        @param photo_detail: 本子章节实体类
        @return: 下载文件夹，为空表示不处理
        """

        # 如果这个章节的本子信息为空，
        # 说明用户可能只是在单独下这一章，
        # 我们不处理这种情况。
        if album_detail is None and photo_detail.from_album:
            return None

        album_detail = album_detail or photo_detail.from_album

        # 下面实现章节文件夹加序号

        # 1. 获取章节在本子中的序号
        index = 0
        for index, each_photo in enumerate(album_detail):
            if each_photo.photo_id == photo_detail.photo_id:
                break

        # 2. 拼接文件夹路径
        Bd = option.dir_tree.Bd

        # 这里可以根据你的flag，进一步判断和定制路径。
        # 简单起见，我们就假设flag == Bd_Author_Title_Image
        # flag = option.dir_tree.flag

        # 下面这行代码保证章节的标题是合法的文件夹名，因为有些章节标题里会存在windows文件夹禁止的字符
        photo_title = fix_windir_name(photo_detail.title.strip())
        # 下载根目录 / 本子作者 / 序号_章节标题 /
        dirpath = f'{Bd}{album_detail.author}/{index + 1}_{photo_title}/'

        # 3. 创建文件夹，因为这个文件夹可能不存在
        mkdir_if_not_exists(dirpath)

        # 4. 返回dirpath
        return dirpath


# 把我们写的MyDownloadAdvice注册到option中
option.register_advice(MyDownloadAdvice())

# 下面是下载漫画代码
download_album(400222, option)
```

上面这段下载代码可以实现你想要的效果，见下图
![advice示例结果](https://user-images.githubusercontent.com/93357912/229875376-79d49eb5-aa41-46e2-a7f0-64174bd92495.png)

最后聊一下这个JmOptionAdvice是个啥。JmOptionAdvice是在v1.0.0引入的一个增强JmOption的机制。因为考虑到单靠配置无法满足一些动态可扩展的场景，于是我在JmOption的一些方法里引入了回调方法。这些回调方法的优先级比配置文件高，可以作为配置文件的补充。在这些回调方法里也可以获取到上下文的一些参数，拥有的权利是很大的，甚至可以重写原方法。
所以，设计这个机制的目的，就是满足一切配置文件不能满足的场景需求。定制下载文件夹就是一个典型场景。

JmOptionAdvice的机制其实并不难，我相信你完全能看懂这部分的源码。
我认为这个回调机制是在工程上的一个很好的设计理念，未来也应该在更多方法里引入这种回调。

最后的最后，你的这个需求也启发了我，也许我们也可以提供一些通用的Advice实现类，实现一些常见的需求，这样会方便有同样想法的人的使用。如果你有兴趣，你可以针对这个点根据你的想法做一些开发，然后提PR。我会很乐意如果能接收到你的PR。

**Comment by hect0x7** [comment]
刚刚发布了jmcomic v1.2.0，优化了上面的一些写法

1. 简化在Adivce中获取photo的序号
```python 
 def decide_image_save_dir(self,
                              option: 'JmOption',
                              album_detail: Optional[JmAlbumDetail],
                              photo_detail: JmPhotoDetail,
                              ) -> StrNone:
    # 省略其他代码

    # 1. 获取序号
    index = photo_detail.album_index

    # 省略其他代码
```

2. 【[章节名称前加序号】新的实现方式，代码更少粒度更小
```python
from jmcomic import *


# 定义一个决定下载路径的函数，参数声明来自 DownloadDirTree.AdditionalHandler
def my_handler(dir_tree: DownloadDirTree,
               album_detail: Optional[JmAlbumDetail],
               photo_detail: JmPhotoDetail,
               ) -> str:
    # 1. 获取序号
    index = photo_detail.album_index

    # 2. 拼接文件夹路径
    # 假设flag == Bd_Author_Title_Image
    Bd = dir_tree.Bd
    # 下面这行代码保证章节的标题是合法的文件夹名，因为有些章节标题里会存在windows文件夹禁止的字符
    photo_title = fix_windir_name(photo_detail.title.strip())
    # 下载根目录 / 本子作者 / 序号_章节标题 /
    dirpath = f'{Bd}{album_detail.author}/{index + 1}_{photo_title}/'

    # 3. 返回dirpath
    return dirpath


option = JmOption.default()

# 定义一个自己的flag
Bd_Author_Index_Title_Image = 999
# 在option中使用自己的flag
option.dir_tree.flag = Bd_Author_Index_Title_Image
# 把这个flag和my_handler绑定
DownloadDirTree.additional_tree_flag_handler_mapping[Bd_Author_Index_Title_Image] = my_handler

# 下面是下载漫画代码
download_album(400222, option)

```

**Comment by tnxl** [comment]
看了下作者的回复时间，深感勤奋，而且写的文案注释非常通顺，逻辑清晰易读，可知作者水品之高，在此感谢作者解惑。

就是看了下作者的演示图片，发现有些序号是存在重复，不知道咋回事，然后图中最下面的第八章前的序号是25是不是跟获取到服务器反馈的时间顺序有关？

**Comment by hect0x7** [comment]
> 看了下作者的回复时间，深感勤奋，而且写的文案注释非常通顺，逻辑清晰易读，可知作者水品之高，在此感谢作者解惑。
> 
> 就是看了下作者的演示图片，发现有些序号是存在重复，不知道咋回事，然后图中最下面的第八章前的序号是25是不是跟获取到服务器反馈的时间顺序有关？

序号的获取确实存在问题，这一点是我的疏忽，没有仔细验证文件夹结果。
准确的说，是这段获取序号的代码存在问题：
```python

  # 1. 获取章节在本子中的序号
  index = 0
  for index, each_photo in enumerate(album_detail):
      if each_photo.photo_id == photo_detail.photo_id:
          break
```
这段采用遍历album_detail的方式确定序号，实际上是遍历了`album_detail.episode_list`，而`episode_list`这个字段是乱序存放了章节数据的。这导致序号的获取出现了问题。

昨晚也是当时考虑到，这种方式获取章节序号太过麻烦，于是去研究了一下禁漫的章节页面，发现有更好的获取序号的方式。
即v1.2.0增加的 `photo_detail.album_index` 属性，这个属性代表章节序号（从1开始），用这个属性可以保证序号无误。
使用这个属性实现的下载序号是正确的：

![Snipaste_2023-04-05_20-58-19](https://user-images.githubusercontent.com/93357912/230087630-1231d479-133d-4309-b810-99e9a788c6f4.png)


最后，感谢你的细心发现~

**Comment by hect0x7** [comment]
关于album_detail.episode_list的乱序，确实和禁漫服务器的返回有关

**Comment by hect0x7** [comment]
> 看了下作者的回复时间，深感勤奋，而且写的文案注释非常通顺，逻辑清晰易读，可知作者水品之高，在此感谢作者解惑。
> 
> 就是看了下作者的演示图片，发现有些序号是存在重复，不知道咋回事，然后图中最下面的第八章前的序号是25是不是跟获取到服务器反馈的时间顺序有关？

这个issue其实还存在最后一个问题，就是`重复序号`的问题。这个问题的答案我刚刚才想明白。
一开始我以为是多线程竞争冒险的问题，结果发现根本不是。这个现象是由2个原因共同导致的。
`1`是章节序号乱序，这个是因为禁漫服务器每次返回的网页代码都不同，导致正则表达式解析得到的章节序号不同。
`2`是多个photo的from_album不是同一个album。

详细解释一下`2`
比如，现在有两个photo，一个对应12章，一个对应13章。
我们的预期应该是，12章的拿到序号12，13章的拿到序号13。
但结果是，12章在自己的album里查找，由于章节序号乱序，12拿到了11。
13章在自己的album里查找，13的album != 12的album，由于章节序号乱序，13也拿到了11。
这样就导致，12章和13章都使用了序号11作为自己的序号，出现了我第一次贴出的图的问题。

以上便是问题的直接原因。

现在假设，多个photo的from_album`是`同一个对象。
由于代码中对章节作了去重，序号11会唯一对应一个photo_id，这样可以保证不同photo拿到的是不同的序号。虽然依然存在乱序问题（v1.2.0后不存在乱序问题了，因为photo获取序号的方式变了）。
那么，为什么多个photo的from_album不是同一个album呢？是刻意而为吗？

其实这里才是真正的bug。

简单解释的话，是因为下面这行代码，把photo对象的from_album变为了None
```python
jm_client.update(photo_detail) # api.py 26行
```

而下载这两行代码，检查了from_album是不是None，如果是None，会通过发请求获取一个`新的album对象`
```python
  if photo_detail.from_album is None:  # api.py 94行
      jm_client.fill_from_album(photo_detail)
```

这就导致了每个photo都有自己的album，才产生了`重复序号`的问题。

下个版本v1.3.0会修复这个问题。

**Comment by tnxl** [comment]
期待作者的下一次更新。
第二点其实我在运行1.2的时候已经发现了，因为有些漫画的图不是一次性就能下载完全的，会漏图。在老的版本应该是1.1或者1.0，因为下载命名文件夹名称的不变，缓存判定图片已经下载过了，我只需要多跑几遍程序就可以下载完全部的图，更新过后因为序号的变化，缓存会误以为没下载过，导致又创建序号不一样的文件夹，再重复下载，导致大小几倍扩大，但是图依旧没有下载完全...

因为不是计算机行业，我平常只能抽空摸下鱼，再加水平有限，所以可能大多时候只能当个伸手党，不能提供一些实质性的帮助，深感抱歉

**Comment by hect0x7** [comment]
没关系，对我来说，能收到一个issue建议，就已经很有意义很有帮助了。
v1.3.0在几个小时前已发布，对序号这件属性的修正应该比较完善了。如果你有空时可以试试看，没试也没关系。
祝你工作/生活顺利啦~
