### ISSUE TITLE
403 爬虫被识别

### ISSUE THREAD

**Issue by moxing69** [hect0x7/JMComic-Crawler-Python#82]
AssertionError: 请求失败，响应状态码为403，原因为: [ip地区禁止访问/爬虫被识别], URL=[https://18comic.vip/album/422866]

就是直接用了下例子，请问需要配置option之类的吗

**Comment by moxing69** [comment]
用浏览器有时候cloudfare也要我认证

**Comment by hect0x7** [comment]
你是用Github Actions跑的吗？

目前我所知道的情况：
1. 用最新的浏览器访问，也会被cf403，登不登录都一样
2. 用Github Actions访问，最近几乎100%被403，我感觉是被封ip了
3. 用自己机器（本地）用脚本访问，不会被403，最近一直都ok

下图是我刚跑的测试，全部通过
![Snipaste_2023-07-31_10-53-22](https://github.com/hect0x7/JMComic-Crawler-Python/assets/93357912/c9052da0-82a9-467d-a055-a3a07eead55b)
这可以证明脚本是可以绕过cf的（甚至可能比最新浏览器绕过效果更好），但是我在Github Actions跑测试秒挂，所以我觉大概率是最近风控了ip。
如果你在本地跑也不行，那大概要配代理了，也就是要配置option

**Comment by hect0x7** [comment]
配置option的方式，你可以用配置文件，或者代码：
```
from jmcomic import *

op = JmOption.construct({
    'client': {
        'postman': {
            'meta_data': {
                'proxies': ProxyBuilder.clash_proxy(),
            }
        }
    }
})
```

**Comment by buiawpkgew1** [comment]
> 配置option的方式，你可以用配置文件，或者代码：
> ```python
> from jmcomic import *
> 
> op = JmOption.construct({
>     'client': {
>         'postman': {
>             'meta_data': {
>                 'proxies': ProxyBuilder.clash_proxy(),
>             }
>         }
>     }
> })
> ```

建议更新一下

**Comment by moxing69** [comment]
我是在海外的ip。

我用了option

proxies: clash


2023-07-31 15:21:30:【error】Failed to perform, ErrCode: 7, Reason: 'Failed to connect to 127.0.0.1 port 22307 after 2040 ms: Connection refused'

我本机也需要弄代理啥的吧，不太会。。。一直在海外从来没弄过本机代理，我看看。

**Comment by hect0x7** [comment]
> 我是在海外的ip。
> 
> 我用了option
> 
> proxies: clash
> 
> 2023-07-31 15:26:40:【error】Failed to perform, ErrCode: 7, Reason: 'Failed to connect to 127.0.0.1 port 7890 after 2037 ms: Connection refused' 2023-07-31 15:26:40:【request_retry】次数: [1/5], 域名: [0 of ['18comic.vip']], 路径: [https://18comic.vip/album/23333], 参数: [{}] 我本机也需要弄代理啥的吧，不太会。。。一直在海外从来没弄过本机代理，我看看。

注意你的代理端口，如下，不太会代码的话建议还是用配置文件
```python
op = JmOption.construct({
    'client': {
        'postman': {
            'meta_data': {
                'proxies': ProxyBuilder.clash_proxy(port='你的端口，例如10809'),
            }
        }
    }
})

```

**Comment by hect0x7** [comment]
> > 配置option的方式，你可以用配置文件，或者代码：
> > ```python
> > from jmcomic import *
> > 
> > op = JmOption.construct({
> >     'client': {
> >         'postman': {
> >             'meta_data': {
> >                 'proxies': ProxyBuilder.clash_proxy(),
> >             }
> >         }
> >     }
> > })
> > ```
> 
> 建议更新一下

已更新

**Comment by moxing69** [comment]
全都试了下，看来我这边都不行，安装了clash，都显示403

**Comment by moxing69** [comment]
解决了
