### ISSUE TITLE
能否按照排行抓取漫画id？

### ISSUE THREAD

**Issue by moxing69** [hect0x7/JMComic-Crawler-Python#84]
谢谢大大开发这么给力的库，我们的项目准备长期依赖这个项目了。

再拷贝制作新的网站，除了拿到最重要的资源以外，用户的浏览体验也比较重要。

请问大大这个库能否支持按照排行榜依次抓取？或者有什么解决方案可以让我们抓取排行榜数据。

**Comment by hect0x7** [comment]
这个项目暂不支持，目前仅支持搜索/下载指定id的本子，而且我也不打算做这个feature。
有一些项目实现了你的这个排行榜功能，比如https://github.com/tonquer/JMComic-qt，你可以参考他们的代码，不过需要你自己实现了。

**Comment by moxing69** [comment]
行没问题的，我也可以自己写爬虫只爬这些数据。感谢。
