### ISSUE TITLE
请问支持压缩图片吗

### ISSUE THREAD

**Issue by moxing69** [hect0x7/JMComic-Crawler-Python#87]
图片的size有些好几mb，请问有api再保存的时候 可以使用自定义的压缩类吗？比如以下

`from PIL import Image

image = Image.open('./00033.png')

image.save('output.jpg', optimize=True, quality=85)`

**Comment by hect0x7** [comment]
新发布了v2.1.9，你可以试试下面的代码
```python
from jmcomic import *


def my_save_image(image: Image, filepath: str):
    """
    你的自定义保存图片函数
    @param image: PIL.Image 对象
    @param filepath: 保存文件路径
    """
    pass


JmImageSupport.save_image = my_save_image

download_album('xxx')

**Comment by moxing69** [comment]
好，我现在试下

**Comment by moxing69** [comment]
> 新发布了v2.1.9，你可以试试下面的代码
> 
> ```python
> from jmcomic import *
> 
> 
> def my_save_image(image: Image, filepath: str):
>     """
>     你的自定义保存图片函数
>     @param image: PIL.Image 对象
>     @param filepath: 保存文件路径
>     """
>     pass
> 
> 
> JmImageSupport.save_image = my_save_image
> 
> download_album('xxx')
> ```

大大，不好意思哈，我对python不是特别熟

我之前的代码是这样的：

import jmcomic
jm_option = jmcomic.create_option('./custom.yml')
jmcomic.download_album(1, jm_option)

然后你给的例子，貌似是from jmcomic import * ，我的代码应怎样更改呀，不好意思。 有点小白。

**Comment by hect0x7** [comment]
这样即可
```python
from jmcomic import *


def my_save_image(image: Image, filepath: str):
    """
    保存图片
    @param image: PIL.Image 对象
    @param filepath: 保存文件路径
    """
    image.save(filepath, optimize=True, quality=85)


JmImageSupport.save_image = my_save_image

jm_option = create_option('./custom.yml')
download_album(1, jm_option)
```

**Comment by moxing69** [comment]
试了下，好像my_save_image 并没有生效，图片保存的还是原始尺寸，这个function好像也没有被执行的样子。是不是我哪里出错了。

如果不好搞，没事哈，大大，我这边可以另外起个cron做图片压缩处理。

**Comment by hect0x7** [comment]
> ```python
> def my_save_image(image: Image, filepath: str):
>     """
>     保存图片
>     @param image: PIL.Image 对象
>     @param filepath: 保存文件路径
>     """
>     image.save(filepath, optimize=True, quality=85)
> ```

不会呀，我用上面的代码可以压缩图片，你试下加入一些输出语句，或者再把quality调小一点
```python
def my_save_image(image: Image, filepath: str):
    """
    保存图片
    @param image: PIL.Image 对象
    @param filepath: 保存文件路径
    """
    print('调用了my_save_image')
    image.save(filepath, optimize=True, quality=20)
```

**Comment by moxing69** [comment]
我先去搞个，外卖，马上再看下。谢谢，周末别加班bro

**Comment by hect0x7** [comment]
可能你没有更新jmcomic模块，在命令行输入下面的命令
```shell
pip install jmcomic -i https://pypi.org/project --upgrade
```

**Comment by moxing69** [comment]
> ```python
>    """
>     保存图片
>     @param image: PIL.Image 对象
>     @param filepath: 保存文件路径
>     """
>     print('调用了my_save_image')
>     image.save(filepath, optimize=True, quality=20)
> ```

已经做啦。pip show jmcomic  显示2.1.9

之前也在那个方法里面写了print, 都不执行，有点奇怪

我卸载了，然后重装，也不执行

**Comment by moxing69** [comment]
没事，我先用cron暂时分开处理下。

可能我这边有些未知问题吧，周末了，就不需要看了，我就关了这个issue。

**Comment by hect0x7** [comment]
我好像找到原因了，你试试下面的代码
```python
from jmcomic import *


def my_save_image(resp, filepath: str, need_convert=True):
    image = JmImageSupport.open_Image(resp.content)
    image.save(filepath, optimize=True, quality=85)


JmImageSupport.save_resp_img = my_save_image

# ...
```

**Comment by moxing69** [comment]
```
def my_save_image(resp, filepath: str, need_convert=True):
    # image = JmImageSupport.open_Image(resp.content)
    # image.save(filepath, optimize=True, quality=85)
    print('something good!')

JmImageSupport.save_resp_img = my_save_image

jm_option = create_option('./custom.yml')
download_album(2, jm_option)
```

不行，terminal里面始终不执行

没事，我已经写好独立的压缩脚本了
