### ISSUE TITLE
执行错误

### ISSUE THREAD

**Issue by jkdfzx** [hect0x7/JMComic-Crawler-Python#94]
执行以下code出现错误，请问是安装问题还是版本有问题?
import jmcomic
jmcomic.download_album('360537') 

![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/139644591/2f133ed5-f083-463e-8bf0-0dfca7427fef)
![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/139644591/5f5d1fcd-3e28-459f-9e77-2aa239c01841)

**Comment by hect0x7** [comment]
执行命令:
```sh
pip install commonX --upgrade
```
